apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - keycloak.yaml
  - kong.yaml
  - kong-bootstrap.yaml
  - httpbin.yaml
  - jenkins-rbac.yaml
  - jenkins.yaml
  - prometheus.yaml
  - loki.yaml
  - promtail.yaml
  - grafana.yaml
  - pulumi-state-pvc.yaml
